
production:
  host: app-production-1.ub.gu.se
  port: 22
  user: apps
  path: '/apps/bestall'
  nvm_path: "/home/apps/.nvm/versions/node/v6.3.1/bin/"

staging:
  host: app-staging-1.ub.gu.se
  port: 22
  user: apps
  path: '/apps/bestall'
  nvm_path: "/home/apps/.nvm/versions/node/v6.3.1/bin/"

lab:
  host: app-lab-1.ub.gu.se
  port: 22
  user: apps
  path: '/apps/bestall'
  nvm_path: "/home/apps/.nvm/versions/node/v6.3.1/bin/"