# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f329894115c225df199211f5e6ff673f45016da7d1da5a70c767af6f65ae7c0f9c70d06ace12567efe35c7c0ce9fb9bae070aac759cd9c301b97fe46e7e5dc

test:
  secret_key_base: 54668892bdd1800a2833200f09127ef899c5fd1b186f5ed98870b792143fc9ea8a7bb1a8aaeff4a07af6a2fd857504083970970d0823787218eaf0928d4321b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
lab:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
